// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: tools.ozone.communication.deleteTemplate
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[jacquard_derive::lexicon]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic,
    Default
)]
#[serde(rename_all = "camelCase")]
pub struct DeleteTemplate<'a> {
    #[serde(borrow)]
    pub id: jacquard_common::CowStr<'a>,
}

/// Response type for
///tools.ozone.communication.deleteTemplate
pub struct DeleteTemplateResponse;
impl jacquard_common::xrpc::XrpcResp for DeleteTemplateResponse {
    const NSID: &'static str = "tools.ozone.communication.deleteTemplate";
    const ENCODING: &'static str = "application/json";
    type Output<'de> = ();
    type Err<'de> = jacquard_common::xrpc::GenericError<'de>;
}

impl<'a> jacquard_common::xrpc::XrpcRequest for DeleteTemplate<'a> {
    const NSID: &'static str = "tools.ozone.communication.deleteTemplate";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Response = DeleteTemplateResponse;
}

/// Endpoint type for
///tools.ozone.communication.deleteTemplate
pub struct DeleteTemplateRequest;
impl jacquard_common::xrpc::XrpcEndpoint for DeleteTemplateRequest {
    const PATH: &'static str = "/xrpc/tools.ozone.communication.deleteTemplate";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Request<'de> = DeleteTemplate<'de>;
    type Response = DeleteTemplateResponse;
}