// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: sh.weaver.notebook.resolveEntry
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic
)]
#[serde(rename_all = "camelCase")]
pub struct ResolveEntry<'a> {
    #[serde(borrow)]
    pub actor: jacquard_common::types::ident::AtIdentifier<'a>,
    #[serde(borrow)]
    pub entry: jacquard_common::CowStr<'a>,
    #[serde(borrow)]
    pub notebook: jacquard_common::CowStr<'a>,
}

pub mod resolve_entry_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Actor;
        type Entry;
        type Notebook;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Actor = Unset;
        type Entry = Unset;
        type Notebook = Unset;
    }
    ///State transition - sets the `actor` field to Set
    pub struct SetActor<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetActor<S> {}
    impl<S: State> State for SetActor<S> {
        type Actor = Set<members::actor>;
        type Entry = S::Entry;
        type Notebook = S::Notebook;
    }
    ///State transition - sets the `entry` field to Set
    pub struct SetEntry<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetEntry<S> {}
    impl<S: State> State for SetEntry<S> {
        type Actor = S::Actor;
        type Entry = Set<members::entry>;
        type Notebook = S::Notebook;
    }
    ///State transition - sets the `notebook` field to Set
    pub struct SetNotebook<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetNotebook<S> {}
    impl<S: State> State for SetNotebook<S> {
        type Actor = S::Actor;
        type Entry = S::Entry;
        type Notebook = Set<members::notebook>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `actor` field
        pub struct actor(());
        ///Marker type for the `entry` field
        pub struct entry(());
        ///Marker type for the `notebook` field
        pub struct notebook(());
    }
}

/// Builder for constructing an instance of this type
pub struct ResolveEntryBuilder<'a, S: resolve_entry_state::State> {
    _phantom_state: ::core::marker::PhantomData<fn() -> S>,
    __unsafe_private_named: (
        ::core::option::Option<jacquard_common::types::ident::AtIdentifier<'a>>,
        ::core::option::Option<jacquard_common::CowStr<'a>>,
        ::core::option::Option<jacquard_common::CowStr<'a>>,
    ),
    _phantom: ::core::marker::PhantomData<&'a ()>,
}

impl<'a> ResolveEntry<'a> {
    /// Create a new builder for this type
    pub fn new() -> ResolveEntryBuilder<'a, resolve_entry_state::Empty> {
        ResolveEntryBuilder::new()
    }
}

impl<'a> ResolveEntryBuilder<'a, resolve_entry_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        ResolveEntryBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: (None, None, None),
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> ResolveEntryBuilder<'a, S>
where
    S: resolve_entry_state::State,
    S::Actor: resolve_entry_state::IsUnset,
{
    /// Set the `actor` field (required)
    pub fn actor(
        mut self,
        value: impl Into<jacquard_common::types::ident::AtIdentifier<'a>>,
    ) -> ResolveEntryBuilder<'a, resolve_entry_state::SetActor<S>> {
        self.__unsafe_private_named.0 = ::core::option::Option::Some(value.into());
        ResolveEntryBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: self.__unsafe_private_named,
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> ResolveEntryBuilder<'a, S>
where
    S: resolve_entry_state::State,
    S::Entry: resolve_entry_state::IsUnset,
{
    /// Set the `entry` field (required)
    pub fn entry(
        mut self,
        value: impl Into<jacquard_common::CowStr<'a>>,
    ) -> ResolveEntryBuilder<'a, resolve_entry_state::SetEntry<S>> {
        self.__unsafe_private_named.1 = ::core::option::Option::Some(value.into());
        ResolveEntryBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: self.__unsafe_private_named,
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> ResolveEntryBuilder<'a, S>
where
    S: resolve_entry_state::State,
    S::Notebook: resolve_entry_state::IsUnset,
{
    /// Set the `notebook` field (required)
    pub fn notebook(
        mut self,
        value: impl Into<jacquard_common::CowStr<'a>>,
    ) -> ResolveEntryBuilder<'a, resolve_entry_state::SetNotebook<S>> {
        self.__unsafe_private_named.2 = ::core::option::Option::Some(value.into());
        ResolveEntryBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: self.__unsafe_private_named,
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> ResolveEntryBuilder<'a, S>
where
    S: resolve_entry_state::State,
    S::Actor: resolve_entry_state::IsSet,
    S::Entry: resolve_entry_state::IsSet,
    S::Notebook: resolve_entry_state::IsSet,
{
    /// Build the final struct
    pub fn build(self) -> ResolveEntry<'a> {
        ResolveEntry {
            actor: self.__unsafe_private_named.0.unwrap(),
            entry: self.__unsafe_private_named.1.unwrap(),
            notebook: self.__unsafe_private_named.2.unwrap(),
        }
    }
}

#[jacquard_derive::lexicon]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic
)]
#[serde(rename_all = "camelCase")]
pub struct ResolveEntryOutput<'a> {
    #[serde(borrow)]
    pub entry: crate::sh_weaver::notebook::EntryView<'a>,
    pub notebook_count: i64,
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    #[serde(borrow)]
    pub notebooks: std::option::Option<
        Vec<crate::sh_weaver::notebook::NotebookView<'a>>,
    >,
    #[serde(borrow)]
    pub record: jacquard_common::types::value::Data<'a>,
}

#[jacquard_derive::open_union]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    thiserror::Error,
    miette::Diagnostic,
    jacquard_derive::IntoStatic
)]
#[serde(tag = "error", content = "message")]
#[serde(bound(deserialize = "'de: 'a"))]
pub enum ResolveEntryError<'a> {
    #[serde(rename = "NotebookNotFound")]
    NotebookNotFound(std::option::Option<jacquard_common::CowStr<'a>>),
    #[serde(rename = "EntryNotFound")]
    EntryNotFound(std::option::Option<jacquard_common::CowStr<'a>>),
}

impl core::fmt::Display for ResolveEntryError<'_> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::NotebookNotFound(msg) => {
                write!(f, "NotebookNotFound")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::EntryNotFound(msg) => {
                write!(f, "EntryNotFound")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::Unknown(err) => write!(f, "Unknown error: {:?}", err),
        }
    }
}

/// Response type for
///sh.weaver.notebook.resolveEntry
pub struct ResolveEntryResponse;
impl jacquard_common::xrpc::XrpcResp for ResolveEntryResponse {
    const NSID: &'static str = "sh.weaver.notebook.resolveEntry";
    const ENCODING: &'static str = "application/json";
    type Output<'de> = ResolveEntryOutput<'de>;
    type Err<'de> = ResolveEntryError<'de>;
}

impl<'a> jacquard_common::xrpc::XrpcRequest for ResolveEntry<'a> {
    const NSID: &'static str = "sh.weaver.notebook.resolveEntry";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Response = ResolveEntryResponse;
}

/// Endpoint type for
///sh.weaver.notebook.resolveEntry
pub struct ResolveEntryRequest;
impl jacquard_common::xrpc::XrpcEndpoint for ResolveEntryRequest {
    const PATH: &'static str = "/xrpc/sh.weaver.notebook.resolveEntry";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Request<'de> = ResolveEntry<'de>;
    type Response = ResolveEntryResponse;
}