// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: sh.weaver.notebook.searchNotebooks
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic
)]
#[serde(rename_all = "camelCase")]
pub struct SearchNotebooks<'a> {
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    #[serde(borrow)]
    pub author: std::option::Option<jacquard_common::types::ident::AtIdentifier<'a>>,
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    #[serde(borrow)]
    pub cursor: std::option::Option<jacquard_common::CowStr<'a>>,
    ///(default: 25, min: 1, max: 100)
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    pub limit: std::option::Option<i64>,
    #[serde(borrow)]
    pub q: jacquard_common::CowStr<'a>,
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    #[serde(borrow)]
    pub rating: std::option::Option<Vec<jacquard_common::CowStr<'a>>>,
    ///(default: "relevance")
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    #[serde(borrow)]
    pub sort: std::option::Option<jacquard_common::CowStr<'a>>,
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    #[serde(borrow)]
    pub tags: std::option::Option<Vec<jacquard_common::CowStr<'a>>>,
}

pub mod search_notebooks_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Q;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Q = Unset;
    }
    ///State transition - sets the `q` field to Set
    pub struct SetQ<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetQ<S> {}
    impl<S: State> State for SetQ<S> {
        type Q = Set<members::q>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `q` field
        pub struct q(());
    }
}

/// Builder for constructing an instance of this type
pub struct SearchNotebooksBuilder<'a, S: search_notebooks_state::State> {
    _phantom_state: ::core::marker::PhantomData<fn() -> S>,
    __unsafe_private_named: (
        ::core::option::Option<jacquard_common::types::ident::AtIdentifier<'a>>,
        ::core::option::Option<jacquard_common::CowStr<'a>>,
        ::core::option::Option<i64>,
        ::core::option::Option<jacquard_common::CowStr<'a>>,
        ::core::option::Option<Vec<jacquard_common::CowStr<'a>>>,
        ::core::option::Option<jacquard_common::CowStr<'a>>,
        ::core::option::Option<Vec<jacquard_common::CowStr<'a>>>,
    ),
    _phantom: ::core::marker::PhantomData<&'a ()>,
}

impl<'a> SearchNotebooks<'a> {
    /// Create a new builder for this type
    pub fn new() -> SearchNotebooksBuilder<'a, search_notebooks_state::Empty> {
        SearchNotebooksBuilder::new()
    }
}

impl<'a> SearchNotebooksBuilder<'a, search_notebooks_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        SearchNotebooksBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: (None, None, None, None, None, None, None),
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S: search_notebooks_state::State> SearchNotebooksBuilder<'a, S> {
    /// Set the `author` field (optional)
    pub fn author(
        mut self,
        value: impl Into<Option<jacquard_common::types::ident::AtIdentifier<'a>>>,
    ) -> Self {
        self.__unsafe_private_named.0 = value.into();
        self
    }
    /// Set the `author` field to an Option value (optional)
    pub fn maybe_author(
        mut self,
        value: Option<jacquard_common::types::ident::AtIdentifier<'a>>,
    ) -> Self {
        self.__unsafe_private_named.0 = value;
        self
    }
}

impl<'a, S: search_notebooks_state::State> SearchNotebooksBuilder<'a, S> {
    /// Set the `cursor` field (optional)
    pub fn cursor(
        mut self,
        value: impl Into<Option<jacquard_common::CowStr<'a>>>,
    ) -> Self {
        self.__unsafe_private_named.1 = value.into();
        self
    }
    /// Set the `cursor` field to an Option value (optional)
    pub fn maybe_cursor(mut self, value: Option<jacquard_common::CowStr<'a>>) -> Self {
        self.__unsafe_private_named.1 = value;
        self
    }
}

impl<'a, S: search_notebooks_state::State> SearchNotebooksBuilder<'a, S> {
    /// Set the `limit` field (optional)
    pub fn limit(mut self, value: impl Into<Option<i64>>) -> Self {
        self.__unsafe_private_named.2 = value.into();
        self
    }
    /// Set the `limit` field to an Option value (optional)
    pub fn maybe_limit(mut self, value: Option<i64>) -> Self {
        self.__unsafe_private_named.2 = value;
        self
    }
}

impl<'a, S> SearchNotebooksBuilder<'a, S>
where
    S: search_notebooks_state::State,
    S::Q: search_notebooks_state::IsUnset,
{
    /// Set the `q` field (required)
    pub fn q(
        mut self,
        value: impl Into<jacquard_common::CowStr<'a>>,
    ) -> SearchNotebooksBuilder<'a, search_notebooks_state::SetQ<S>> {
        self.__unsafe_private_named.3 = ::core::option::Option::Some(value.into());
        SearchNotebooksBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: self.__unsafe_private_named,
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S: search_notebooks_state::State> SearchNotebooksBuilder<'a, S> {
    /// Set the `rating` field (optional)
    pub fn rating(
        mut self,
        value: impl Into<Option<Vec<jacquard_common::CowStr<'a>>>>,
    ) -> Self {
        self.__unsafe_private_named.4 = value.into();
        self
    }
    /// Set the `rating` field to an Option value (optional)
    pub fn maybe_rating(
        mut self,
        value: Option<Vec<jacquard_common::CowStr<'a>>>,
    ) -> Self {
        self.__unsafe_private_named.4 = value;
        self
    }
}

impl<'a, S: search_notebooks_state::State> SearchNotebooksBuilder<'a, S> {
    /// Set the `sort` field (optional)
    pub fn sort(
        mut self,
        value: impl Into<Option<jacquard_common::CowStr<'a>>>,
    ) -> Self {
        self.__unsafe_private_named.5 = value.into();
        self
    }
    /// Set the `sort` field to an Option value (optional)
    pub fn maybe_sort(mut self, value: Option<jacquard_common::CowStr<'a>>) -> Self {
        self.__unsafe_private_named.5 = value;
        self
    }
}

impl<'a, S: search_notebooks_state::State> SearchNotebooksBuilder<'a, S> {
    /// Set the `tags` field (optional)
    pub fn tags(
        mut self,
        value: impl Into<Option<Vec<jacquard_common::CowStr<'a>>>>,
    ) -> Self {
        self.__unsafe_private_named.6 = value.into();
        self
    }
    /// Set the `tags` field to an Option value (optional)
    pub fn maybe_tags(
        mut self,
        value: Option<Vec<jacquard_common::CowStr<'a>>>,
    ) -> Self {
        self.__unsafe_private_named.6 = value;
        self
    }
}

impl<'a, S> SearchNotebooksBuilder<'a, S>
where
    S: search_notebooks_state::State,
    S::Q: search_notebooks_state::IsSet,
{
    /// Build the final struct
    pub fn build(self) -> SearchNotebooks<'a> {
        SearchNotebooks {
            author: self.__unsafe_private_named.0,
            cursor: self.__unsafe_private_named.1,
            limit: self.__unsafe_private_named.2,
            q: self.__unsafe_private_named.3.unwrap(),
            rating: self.__unsafe_private_named.4,
            sort: self.__unsafe_private_named.5,
            tags: self.__unsafe_private_named.6,
        }
    }
}

#[jacquard_derive::lexicon]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic
)]
#[serde(rename_all = "camelCase")]
pub struct SearchNotebooksOutput<'a> {
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    #[serde(borrow)]
    pub cursor: std::option::Option<jacquard_common::CowStr<'a>>,
    #[serde(borrow)]
    pub notebooks: Vec<crate::sh_weaver::notebook::NotebookView<'a>>,
}

/// Response type for
///sh.weaver.notebook.searchNotebooks
pub struct SearchNotebooksResponse;
impl jacquard_common::xrpc::XrpcResp for SearchNotebooksResponse {
    const NSID: &'static str = "sh.weaver.notebook.searchNotebooks";
    const ENCODING: &'static str = "application/json";
    type Output<'de> = SearchNotebooksOutput<'de>;
    type Err<'de> = jacquard_common::xrpc::GenericError<'de>;
}

impl<'a> jacquard_common::xrpc::XrpcRequest for SearchNotebooks<'a> {
    const NSID: &'static str = "sh.weaver.notebook.searchNotebooks";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Response = SearchNotebooksResponse;
}

/// Endpoint type for
///sh.weaver.notebook.searchNotebooks
pub struct SearchNotebooksRequest;
impl jacquard_common::xrpc::XrpcEndpoint for SearchNotebooksRequest {
    const PATH: &'static str = "/xrpc/sh.weaver.notebook.searchNotebooks";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Request<'de> = SearchNotebooks<'de>;
    type Response = SearchNotebooksResponse;
}