// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: com.atproto.admin.updateAccountPassword
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[jacquard_derive::lexicon]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic
)]
#[serde(rename_all = "camelCase")]
pub struct UpdateAccountPassword<'a> {
    #[serde(borrow)]
    pub did: jacquard_common::types::string::Did<'a>,
    #[serde(borrow)]
    pub password: jacquard_common::CowStr<'a>,
}

pub mod update_account_password_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Password;
        type Did;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Password = Unset;
        type Did = Unset;
    }
    ///State transition - sets the `password` field to Set
    pub struct SetPassword<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetPassword<S> {}
    impl<S: State> State for SetPassword<S> {
        type Password = Set<members::password>;
        type Did = S::Did;
    }
    ///State transition - sets the `did` field to Set
    pub struct SetDid<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetDid<S> {}
    impl<S: State> State for SetDid<S> {
        type Password = S::Password;
        type Did = Set<members::did>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `password` field
        pub struct password(());
        ///Marker type for the `did` field
        pub struct did(());
    }
}

/// Builder for constructing an instance of this type
pub struct UpdateAccountPasswordBuilder<'a, S: update_account_password_state::State> {
    _phantom_state: ::core::marker::PhantomData<fn() -> S>,
    __unsafe_private_named: (
        ::core::option::Option<jacquard_common::types::string::Did<'a>>,
        ::core::option::Option<jacquard_common::CowStr<'a>>,
    ),
    _phantom: ::core::marker::PhantomData<&'a ()>,
}

impl<'a> UpdateAccountPassword<'a> {
    /// Create a new builder for this type
    pub fn new() -> UpdateAccountPasswordBuilder<
        'a,
        update_account_password_state::Empty,
    > {
        UpdateAccountPasswordBuilder::new()
    }
}

impl<'a> UpdateAccountPasswordBuilder<'a, update_account_password_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        UpdateAccountPasswordBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: (None, None),
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> UpdateAccountPasswordBuilder<'a, S>
where
    S: update_account_password_state::State,
    S::Did: update_account_password_state::IsUnset,
{
    /// Set the `did` field (required)
    pub fn did(
        mut self,
        value: impl Into<jacquard_common::types::string::Did<'a>>,
    ) -> UpdateAccountPasswordBuilder<'a, update_account_password_state::SetDid<S>> {
        self.__unsafe_private_named.0 = ::core::option::Option::Some(value.into());
        UpdateAccountPasswordBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: self.__unsafe_private_named,
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> UpdateAccountPasswordBuilder<'a, S>
where
    S: update_account_password_state::State,
    S::Password: update_account_password_state::IsUnset,
{
    /// Set the `password` field (required)
    pub fn password(
        mut self,
        value: impl Into<jacquard_common::CowStr<'a>>,
    ) -> UpdateAccountPasswordBuilder<
        'a,
        update_account_password_state::SetPassword<S>,
    > {
        self.__unsafe_private_named.1 = ::core::option::Option::Some(value.into());
        UpdateAccountPasswordBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: self.__unsafe_private_named,
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> UpdateAccountPasswordBuilder<'a, S>
where
    S: update_account_password_state::State,
    S::Password: update_account_password_state::IsSet,
    S::Did: update_account_password_state::IsSet,
{
    /// Build the final struct
    pub fn build(self) -> UpdateAccountPassword<'a> {
        UpdateAccountPassword {
            did: self.__unsafe_private_named.0.unwrap(),
            password: self.__unsafe_private_named.1.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data
    pub fn build_with_data(
        self,
        extra_data: std::collections::BTreeMap<
            jacquard_common::smol_str::SmolStr,
            jacquard_common::types::value::Data<'a>,
        >,
    ) -> UpdateAccountPassword<'a> {
        UpdateAccountPassword {
            did: self.__unsafe_private_named.0.unwrap(),
            password: self.__unsafe_private_named.1.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}

/// Response type for
///com.atproto.admin.updateAccountPassword
pub struct UpdateAccountPasswordResponse;
impl jacquard_common::xrpc::XrpcResp for UpdateAccountPasswordResponse {
    const NSID: &'static str = "com.atproto.admin.updateAccountPassword";
    const ENCODING: &'static str = "application/json";
    type Output<'de> = ();
    type Err<'de> = jacquard_common::xrpc::GenericError<'de>;
}

impl<'a> jacquard_common::xrpc::XrpcRequest for UpdateAccountPassword<'a> {
    const NSID: &'static str = "com.atproto.admin.updateAccountPassword";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Response = UpdateAccountPasswordResponse;
}

/// Endpoint type for
///com.atproto.admin.updateAccountPassword
pub struct UpdateAccountPasswordRequest;
impl jacquard_common::xrpc::XrpcEndpoint for UpdateAccountPasswordRequest {
    const PATH: &'static str = "/xrpc/com.atproto.admin.updateAccountPassword";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Request<'de> = UpdateAccountPassword<'de>;
    type Response = UpdateAccountPasswordResponse;
}