// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: app.bsky.unspecced.getSuggestedStarterPacks
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic
)]
#[serde(rename_all = "camelCase")]
pub struct GetSuggestedStarterPacks {
    ///(default: 10, min: 1, max: 25)
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    pub limit: std::option::Option<i64>,
}

pub mod get_suggested_starter_packs_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {}
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {}
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {}
}

/// Builder for constructing an instance of this type
pub struct GetSuggestedStarterPacksBuilder<S: get_suggested_starter_packs_state::State> {
    _phantom_state: ::core::marker::PhantomData<fn() -> S>,
    __unsafe_private_named: (::core::option::Option<i64>,),
}

impl GetSuggestedStarterPacks {
    /// Create a new builder for this type
    pub fn new() -> GetSuggestedStarterPacksBuilder<
        get_suggested_starter_packs_state::Empty,
    > {
        GetSuggestedStarterPacksBuilder::new()
    }
}

impl GetSuggestedStarterPacksBuilder<get_suggested_starter_packs_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        GetSuggestedStarterPacksBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: (None,),
        }
    }
}

impl<S: get_suggested_starter_packs_state::State> GetSuggestedStarterPacksBuilder<S> {
    /// Set the `limit` field (optional)
    pub fn limit(mut self, value: impl Into<Option<i64>>) -> Self {
        self.__unsafe_private_named.0 = value.into();
        self
    }
    /// Set the `limit` field to an Option value (optional)
    pub fn maybe_limit(mut self, value: Option<i64>) -> Self {
        self.__unsafe_private_named.0 = value;
        self
    }
}

impl<S> GetSuggestedStarterPacksBuilder<S>
where
    S: get_suggested_starter_packs_state::State,
{
    /// Build the final struct
    pub fn build(self) -> GetSuggestedStarterPacks {
        GetSuggestedStarterPacks {
            limit: self.__unsafe_private_named.0,
        }
    }
}

#[jacquard_derive::lexicon]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic
)]
#[serde(rename_all = "camelCase")]
pub struct GetSuggestedStarterPacksOutput<'a> {
    #[serde(borrow)]
    pub starter_packs: Vec<crate::app_bsky::graph::StarterPackView<'a>>,
}

/// Response type for
///app.bsky.unspecced.getSuggestedStarterPacks
pub struct GetSuggestedStarterPacksResponse;
impl jacquard_common::xrpc::XrpcResp for GetSuggestedStarterPacksResponse {
    const NSID: &'static str = "app.bsky.unspecced.getSuggestedStarterPacks";
    const ENCODING: &'static str = "application/json";
    type Output<'de> = GetSuggestedStarterPacksOutput<'de>;
    type Err<'de> = jacquard_common::xrpc::GenericError<'de>;
}

impl jacquard_common::xrpc::XrpcRequest for GetSuggestedStarterPacks {
    const NSID: &'static str = "app.bsky.unspecced.getSuggestedStarterPacks";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Response = GetSuggestedStarterPacksResponse;
}

/// Endpoint type for
///app.bsky.unspecced.getSuggestedStarterPacks
pub struct GetSuggestedStarterPacksRequest;
impl jacquard_common::xrpc::XrpcEndpoint for GetSuggestedStarterPacksRequest {
    const PATH: &'static str = "/xrpc/app.bsky.unspecced.getSuggestedStarterPacks";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Request<'de> = GetSuggestedStarterPacks;
    type Response = GetSuggestedStarterPacksResponse;
}