// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: chat.bsky.actor.declaration
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

/// A declaration of a Bluesky chat account.
#[jacquard_derive::lexicon]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic
)]
#[serde(rename_all = "camelCase")]
pub struct Declaration<'a> {
    #[serde(borrow)]
    pub allow_incoming: DeclarationAllowIncoming<'a>,
}

pub mod declaration_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type AllowIncoming;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type AllowIncoming = Unset;
    }
    ///State transition - sets the `allow_incoming` field to Set
    pub struct SetAllowIncoming<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetAllowIncoming<S> {}
    impl<S: State> State for SetAllowIncoming<S> {
        type AllowIncoming = Set<members::allow_incoming>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `allow_incoming` field
        pub struct allow_incoming(());
    }
}

/// Builder for constructing an instance of this type
pub struct DeclarationBuilder<'a, S: declaration_state::State> {
    _phantom_state: ::core::marker::PhantomData<fn() -> S>,
    __unsafe_private_named: (::core::option::Option<DeclarationAllowIncoming<'a>>,),
    _phantom: ::core::marker::PhantomData<&'a ()>,
}

impl<'a> Declaration<'a> {
    /// Create a new builder for this type
    pub fn new() -> DeclarationBuilder<'a, declaration_state::Empty> {
        DeclarationBuilder::new()
    }
}

impl<'a> DeclarationBuilder<'a, declaration_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        DeclarationBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: (None,),
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> DeclarationBuilder<'a, S>
where
    S: declaration_state::State,
    S::AllowIncoming: declaration_state::IsUnset,
{
    /// Set the `allowIncoming` field (required)
    pub fn allow_incoming(
        mut self,
        value: impl Into<DeclarationAllowIncoming<'a>>,
    ) -> DeclarationBuilder<'a, declaration_state::SetAllowIncoming<S>> {
        self.__unsafe_private_named.0 = ::core::option::Option::Some(value.into());
        DeclarationBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: self.__unsafe_private_named,
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> DeclarationBuilder<'a, S>
where
    S: declaration_state::State,
    S::AllowIncoming: declaration_state::IsSet,
{
    /// Build the final struct
    pub fn build(self) -> Declaration<'a> {
        Declaration {
            allow_incoming: self.__unsafe_private_named.0.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data
    pub fn build_with_data(
        self,
        extra_data: std::collections::BTreeMap<
            jacquard_common::smol_str::SmolStr,
            jacquard_common::types::value::Data<'a>,
        >,
    ) -> Declaration<'a> {
        Declaration {
            allow_incoming: self.__unsafe_private_named.0.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}

impl<'a> Declaration<'a> {
    pub fn uri(
        uri: impl Into<jacquard_common::CowStr<'a>>,
    ) -> Result<
        jacquard_common::types::uri::RecordUri<'a, DeclarationRecord>,
        jacquard_common::types::uri::UriError,
    > {
        jacquard_common::types::uri::RecordUri::try_from_uri(
            jacquard_common::types::string::AtUri::new_cow(uri.into())?,
        )
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum DeclarationAllowIncoming<'a> {
    All,
    None,
    Following,
    Other(jacquard_common::CowStr<'a>),
}

impl<'a> DeclarationAllowIncoming<'a> {
    pub fn as_str(&self) -> &str {
        match self {
            Self::All => "all",
            Self::None => "none",
            Self::Following => "following",
            Self::Other(s) => s.as_ref(),
        }
    }
}

impl<'a> From<&'a str> for DeclarationAllowIncoming<'a> {
    fn from(s: &'a str) -> Self {
        match s {
            "all" => Self::All,
            "none" => Self::None,
            "following" => Self::Following,
            _ => Self::Other(jacquard_common::CowStr::from(s)),
        }
    }
}

impl<'a> From<String> for DeclarationAllowIncoming<'a> {
    fn from(s: String) -> Self {
        match s.as_str() {
            "all" => Self::All,
            "none" => Self::None,
            "following" => Self::Following,
            _ => Self::Other(jacquard_common::CowStr::from(s)),
        }
    }
}

impl<'a> core::fmt::Display for DeclarationAllowIncoming<'a> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, "{}", self.as_str())
    }
}

impl<'a> AsRef<str> for DeclarationAllowIncoming<'a> {
    fn as_ref(&self) -> &str {
        self.as_str()
    }
}

impl<'a> serde::Serialize for DeclarationAllowIncoming<'a> {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de, 'a> serde::Deserialize<'de> for DeclarationAllowIncoming<'a>
where
    'de: 'a,
{
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let s = <&'de str>::deserialize(deserializer)?;
        Ok(Self::from(s))
    }
}

impl<'a> Default for DeclarationAllowIncoming<'a> {
    fn default() -> Self {
        Self::Other(Default::default())
    }
}

impl jacquard_common::IntoStatic for DeclarationAllowIncoming<'_> {
    type Output = DeclarationAllowIncoming<'static>;
    fn into_static(self) -> Self::Output {
        match self {
            DeclarationAllowIncoming::All => DeclarationAllowIncoming::All,
            DeclarationAllowIncoming::None => DeclarationAllowIncoming::None,
            DeclarationAllowIncoming::Following => DeclarationAllowIncoming::Following,
            DeclarationAllowIncoming::Other(v) => {
                DeclarationAllowIncoming::Other(v.into_static())
            }
        }
    }
}

/// Typed wrapper for GetRecord response with this collection's record type.
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic
)]
#[serde(rename_all = "camelCase")]
pub struct DeclarationGetRecordOutput<'a> {
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    #[serde(borrow)]
    pub cid: std::option::Option<jacquard_common::types::string::Cid<'a>>,
    #[serde(borrow)]
    pub uri: jacquard_common::types::string::AtUri<'a>,
    #[serde(borrow)]
    pub value: Declaration<'a>,
}

impl From<DeclarationGetRecordOutput<'_>> for Declaration<'_> {
    fn from(output: DeclarationGetRecordOutput<'_>) -> Self {
        use jacquard_common::IntoStatic;
        output.value.into_static()
    }
}

impl jacquard_common::types::collection::Collection for Declaration<'_> {
    const NSID: &'static str = "chat.bsky.actor.declaration";
    type Record = DeclarationRecord;
}

/// Marker type for deserializing records from this collection.
#[derive(Debug, serde::Serialize, serde::Deserialize)]
pub struct DeclarationRecord;
impl jacquard_common::xrpc::XrpcResp for DeclarationRecord {
    const NSID: &'static str = "chat.bsky.actor.declaration";
    const ENCODING: &'static str = "application/json";
    type Output<'de> = DeclarationGetRecordOutput<'de>;
    type Err<'de> = jacquard_common::types::collection::RecordError<'de>;
}

impl jacquard_common::types::collection::Collection for DeclarationRecord {
    const NSID: &'static str = "chat.bsky.actor.declaration";
    type Record = DeclarationRecord;
}

impl<'a> ::jacquard_lexicon::schema::LexiconSchema for Declaration<'a> {
    fn nsid() -> &'static str {
        "chat.bsky.actor.declaration"
    }
    fn def_name() -> &'static str {
        "main"
    }
    fn lexicon_doc() -> ::jacquard_lexicon::lexicon::LexiconDoc<'static> {
        lexicon_doc_chat_bsky_actor_declaration()
    }
    fn validate(
        &self,
    ) -> ::core::result::Result<(), ::jacquard_lexicon::validation::ConstraintError> {
        Ok(())
    }
}

fn lexicon_doc_chat_bsky_actor_declaration() -> ::jacquard_lexicon::lexicon::LexiconDoc<
    'static,
> {
    ::jacquard_lexicon::lexicon::LexiconDoc {
        lexicon: ::jacquard_lexicon::lexicon::Lexicon::Lexicon1,
        id: ::jacquard_common::CowStr::new_static("chat.bsky.actor.declaration"),
        revision: None,
        description: None,
        defs: {
            let mut map = ::alloc::collections::BTreeMap::new();
            map.insert(
                ::jacquard_common::smol_str::SmolStr::new_static("main"),
                ::jacquard_lexicon::lexicon::LexUserType::Record(::jacquard_lexicon::lexicon::LexRecord {
                    description: Some(
                        ::jacquard_common::CowStr::new_static(
                            "A declaration of a Bluesky chat account.",
                        ),
                    ),
                    key: Some(::jacquard_common::CowStr::new_static("literal:self")),
                    record: ::jacquard_lexicon::lexicon::LexRecordRecord::Object(::jacquard_lexicon::lexicon::LexObject {
                        description: None,
                        required: Some(
                            vec![
                                ::jacquard_common::smol_str::SmolStr::new_static("allowIncoming")
                            ],
                        ),
                        nullable: None,
                        properties: {
                            #[allow(unused_mut)]
                            let mut map = ::alloc::collections::BTreeMap::new();
                            map.insert(
                                ::jacquard_common::smol_str::SmolStr::new_static(
                                    "allowIncoming",
                                ),
                                ::jacquard_lexicon::lexicon::LexObjectProperty::String(::jacquard_lexicon::lexicon::LexString {
                                    description: None,
                                    format: None,
                                    default: None,
                                    min_length: None,
                                    max_length: None,
                                    min_graphemes: None,
                                    max_graphemes: None,
                                    r#enum: None,
                                    r#const: None,
                                    known_values: None,
                                }),
                            );
                            map
                        },
                    }),
                }),
            );
            map
        },
    }
}