// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: com.atproto.temp.addReservedHandle
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[jacquard_derive::lexicon]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic,
    Default
)]
#[serde(rename_all = "camelCase")]
pub struct AddReservedHandle<'a> {
    #[serde(borrow)]
    pub handle: jacquard_common::CowStr<'a>,
}

#[jacquard_derive::lexicon]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic,
    Default
)]
#[serde(rename_all = "camelCase")]
pub struct AddReservedHandleOutput<'a> {}
/// Response type for
///com.atproto.temp.addReservedHandle
pub struct AddReservedHandleResponse;
impl jacquard_common::xrpc::XrpcResp for AddReservedHandleResponse {
    const NSID: &'static str = "com.atproto.temp.addReservedHandle";
    const ENCODING: &'static str = "application/json";
    type Output<'de> = AddReservedHandleOutput<'de>;
    type Err<'de> = jacquard_common::xrpc::GenericError<'de>;
}

impl<'a> jacquard_common::xrpc::XrpcRequest for AddReservedHandle<'a> {
    const NSID: &'static str = "com.atproto.temp.addReservedHandle";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Response = AddReservedHandleResponse;
}

/// Endpoint type for
///com.atproto.temp.addReservedHandle
pub struct AddReservedHandleRequest;
impl jacquard_common::xrpc::XrpcEndpoint for AddReservedHandleRequest {
    const PATH: &'static str = "/xrpc/com.atproto.temp.addReservedHandle";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Request<'de> = AddReservedHandle<'de>;
    type Response = AddReservedHandleResponse;
}