// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: com.atproto.server.requestPasswordReset
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[jacquard_derive::lexicon]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic,
    Default
)]
#[serde(rename_all = "camelCase")]
pub struct RequestPasswordReset<'a> {
    #[serde(borrow)]
    pub email: jacquard_common::CowStr<'a>,
}

/// Response type for
///com.atproto.server.requestPasswordReset
pub struct RequestPasswordResetResponse;
impl jacquard_common::xrpc::XrpcResp for RequestPasswordResetResponse {
    const NSID: &'static str = "com.atproto.server.requestPasswordReset";
    const ENCODING: &'static str = "application/json";
    type Output<'de> = ();
    type Err<'de> = jacquard_common::xrpc::GenericError<'de>;
}

impl<'a> jacquard_common::xrpc::XrpcRequest for RequestPasswordReset<'a> {
    const NSID: &'static str = "com.atproto.server.requestPasswordReset";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Response = RequestPasswordResetResponse;
}

/// Endpoint type for
///com.atproto.server.requestPasswordReset
pub struct RequestPasswordResetRequest;
impl jacquard_common::xrpc::XrpcEndpoint for RequestPasswordResetRequest {
    const PATH: &'static str = "/xrpc/com.atproto.server.requestPasswordReset";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Request<'de> = RequestPasswordReset<'de>;
    type Response = RequestPasswordResetResponse;
}