// @generated - This file is generated by esquema-codegen (forked from atrium-codegen). DO NOT EDIT.
//!Definitions for the `sh.tangled.actor` namespace.
pub mod profile;
#[derive(Debug)]
pub struct Profile;
impl atrium_api::types::Collection for Profile {
    const NSID: &'static str = "sh.tangled.actor.profile";
    type Record = profile::Record;
}
